=head1 NAME

debget - Fetch a .deb for a package in APT's database

=head1 SYNOPSIS

B<debget> I<package> [I<package> ...]

=head1 DESCRIPTION

B<debget> fetches a .deb for one or more packages from an Debian mirror.
It uses apt-get(1) to find out the URL so it will download the same version
from the same server as I<apt-get> would do. The .deb will be downloaded with
curl(1) and stored in your current working directory.

=head1 AUTHOR

Matt Zimmerman <mdz@debian.org>

This manpage was written by Frank Lichtenheld <frank@lichtenheld>.

=head1 COPYRIGHT AND LICENCE

Copyright (C) 2001 Matt Zimmerman <mdz@debian.org>.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

On Debian systems, a copy of the GNU General Public License may be
found in /usr/share/common-licenses/GPL.

=head1 SEE ALSO

apt-get(1), curl(1)
