#!/bin/sh
#
#  Copyright (C) 2008  Thadeu Lima de Souza Cascardo <cascardo@holoscopio.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

VERSION="0.1"

version()
{
  echo "dhomepage version $VERSION"
  echo "dhomepage is licensed under the GNU General Public License"
  echo "version 2 or later"
}

usage()
{
  echo "dhomepage PACKAGE"
  echo ""
  echo "--version	Show version information"
  echo "--help		Show this help message"
  echo ""
}

PACKAGE="$1"

if [ -z "$PACKAGE" ]; then
  usage
  exit 0
fi

case "$1" in
	--help)
		usage
		exit 0
		;;
	--version)
		version
		exit 0
		;;
esac

HOMEPAGE=`grep-aptavail -PX $PACKAGE -s Homepage | sed 's,^Homepage: ,,'`

if [ -z "$HOMEPAGE" ]; then
  HOMEPAGE=`grep-aptavail -PX $PACKAGE -s Description | \
    sed -n '/^  Homepage: /{s,^  Homepage: ,,;p}'`
fi

if [ -z "$HOMEPAGE" ]; then
  echo "$PACKAGE has no homepage"
  exit 1
fi

sensible-browser "$HOMEPAGE"
