#!/bin/sh
#
# copy this script into /etc/cron.daily
#
# if you also install the unattended-upgrades package then 
# services that need it will be automatically restarted
# after a security update

tmp_output=`mktemp /tmp/cron-daily-restart-services.XXXXXX`

restart-services >$tmp_output 2>&1
exit_status=$?
if [ "$exit_status" != 0 ]; then
  cat $tmp_output
fi

rm $tmp_output 
exit $exit_status
