#!/bin/sh
#
# copy this script into /etc/cron.daily
#
# if you also install the unattended-upgrades package then 
# services that need it will be automatically restarted
# after a security update

tmp_output=`mktemp /tmp/cron-daily-restart-services.XXXXXX`
restart-services >$tmp_output 2>&1
[ "$1" != 0 ] && cat $tmp_output
rm $tmp_output 
